REG_C100 = "C100"

IDX_C100 = {
    "ind_oper": 0,
    "ind_emit": 1,
    "cod_part": 2,
    "cod_mod": 3,
    "cod_sit": 4,
    "serie": 5,
    "num_doc": 6,
    "chave_nfe": 7,
    "dt_doc": 8,
    "dt_e_s": 9,
    "vl_doc": 10,
    "ind_pgto": 11,
    "vl_desc": 12,
    "vl_abat_nt": 13,
    "vl_merc": 14,
    "ind_frt": 15,
    "vl_frt": 16,
    "vl_seg": 17,
    "vl_out_da": 18,
    "vl_bc_icms": 19,
    "vl_icms": 20,
    "vl_bc_icms_st": 21,
    "vl_icms_st": 22,
    "vl_ipi": 23,
    "vl_pis": 24,
    "vl_cofins": 25,
    "vl_pis_st": 26,
    "vl_cofins_st": 27,
}