TIPO_ERRO = "ERRO"
TIPO_ALERTA = "ALERTA"
TIPO_OPORTUNIDADE = "OPORTUNIDADE"

TIPOS_APONTAMENTO_VALIDOS = {
    TIPO_ERRO,
    TIPO_ALERTA,
    TIPO_OPORTUNIDADE,
}

# =========================
# Agrupadores lógicos
# =========================

GRUPO_EXPORTACAO = "EXPORTACAO"
GRUPO_CAFE = "CAFE"
GRUPO_POSTO = "POSTO"
GRUPO_ENTRADAS = "ENTRADAS"

# Subgrupos (opcional, mas recomendado)
SUBGRUPO_RESSARCIMENTO = "RESSARCIMENTO"
SUBGRUPO_CONSISTENCIA = "CONSISTENCIA"
SUBGRUPO_C190 = "C190"
SUBGRUPO_C100 = "C100"

ACAO_OVERRIDE_BASE_POR_CST = "OVERRIDE_BASE_POR_CST"


# Domínios do motor fiscal

DOM_GERAL = "GERAL"
DOM_SUP = "SUP"
DOM_AGRO = "AGRO"
DOM_CAFE = "CAFE"
DOM_POSTO = "POSTO"
DOM_TRANSP = "TRANSP"
DOM_REVENDA_GAS = "REVENDA_GAS"

DOMINIOS_VALIDOS = {
    DOM_GERAL,
    DOM_SUP,
    DOM_AGRO,
    DOM_CAFE,
    DOM_POSTO,
    DOM_TRANSP,
    DOM_REVENDA_GAS,
}

DOMINIOS_LC192 = {"TRANSP", "POSTO", "REVENDA_GAS"}

REGS_M_RELEVANTES = {
    "M100", "M105", "M110", "M115",
    "M200", "M205", "M210",
    "M500", "M505", "M510", "M515",
    "M600", "M605", "M610",
    "M400", "M410", "M800", "M810",
}
